# .github/FUNDING.yml

 github: ["tejindrakhatri1"]

# Custom funding links (these work for everyone)
custom:
  - "https://www.buymeacoffee.com/tejindra"
  - "https://paypal.me/tejindrakhatri"
  - "https://ko-fi.com/tejindra"
